# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: book.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'book.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x04\x62ook\"\x19\n\x0b\x42ookRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"/\n\x0eNewBookRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\"1\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\"(\n\x0c\x42ookResponse\x12\x18\n\x04\x62ook\x18\x01 \x01(\x0b\x32\n.book.Book\"\x07\n\x05\x45mpty\"-\n\x10\x42ookListResponse\x12\x19\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\n.book.Book2\xa6\x01\n\x0b\x42ookService\x12\x30\n\x07GetBook\x12\x11.book.BookRequest\x1a\x12.book.BookResponse\x12\x30\n\tListBooks\x12\x0b.book.Empty\x1a\x16.book.BookListResponse\x12\x33\n\x07\x41\x64\x64\x42ook\x12\x14.book.NewBookRequest\x1a\x12.book.BookResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKREQUEST']._serialized_start=20
  _globals['_BOOKREQUEST']._serialized_end=45
  _globals['_NEWBOOKREQUEST']._serialized_start=47
  _globals['_NEWBOOKREQUEST']._serialized_end=94
  _globals['_BOOK']._serialized_start=96
  _globals['_BOOK']._serialized_end=145
  _globals['_BOOKRESPONSE']._serialized_start=147
  _globals['_BOOKRESPONSE']._serialized_end=187
  _globals['_EMPTY']._serialized_start=189
  _globals['_EMPTY']._serialized_end=196
  _globals['_BOOKLISTRESPONSE']._serialized_start=198
  _globals['_BOOKLISTRESPONSE']._serialized_end=243
  _globals['_BOOKSERVICE']._serialized_start=246
  _globals['_BOOKSERVICE']._serialized_end=412
# @@protoc_insertion_point(module_scope)
