# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\")\n\x11\x43\x61lculatorRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\"$\n\x12\x43\x61lculatorResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32\xb8\x02\n\x11\x43\x61lculatorService\x12\x44\n\x03\x41\x64\x64\x12\x1d.calculator.CalculatorRequest\x1a\x1e.calculator.CalculatorResponse\x12I\n\x08Subtract\x12\x1d.calculator.CalculatorRequest\x1a\x1e.calculator.CalculatorResponse\x12I\n\x08Multiply\x12\x1d.calculator.CalculatorRequest\x1a\x1e.calculator.CalculatorResponse\x12G\n\x06\x44ivide\x12\x1d.calculator.CalculatorRequest\x1a\x1e.calculator.CalculatorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CALCULATORREQUEST']._serialized_start=32
  _globals['_CALCULATORREQUEST']._serialized_end=73
  _globals['_CALCULATORRESPONSE']._serialized_start=75
  _globals['_CALCULATORRESPONSE']._serialized_end=111
  _globals['_CALCULATORSERVICE']._serialized_start=114
  _globals['_CALCULATORSERVICE']._serialized_end=426
# @@protoc_insertion_point(module_scope)
